@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM After cloning the Win10 WIMS template, personalize this guest for one radio seat.
REM Usage (elevated recommended for rename):
REM   Set-SeatAfterClone.cmd SEAT-ID [WSJT-RIG-NAME] [flex50|ic9700-144]
REM Examples:
REM   Set-SeatAfterClone.cmd W10VM-50 WSJTX-50 flex50
REM   Set-SeatAfterClone.cmd W10VM-144 WSJTX-144 ic9700-144
REM   Set-SeatAfterClone.cmd IC9700-144
REM
REM What it does:
REM   1) Writes seat-common.cmd + radio-*.cmd
REM   2) Renames the computer to SEAT-ID (needs reboot)
REM   3) Ensures Startup\WIMS Seat.lnk for the chosen pack
REM   4) Points Desktop / Start Menu WSJT-X shortcuts at Start-WSJTX.cmd
REM Does NOT change Proxmox USB/network or radio drivers.

cd /d "%~dp0"
set "HERE=%~dp0"
set "SEAT=%~1"
set "RIG=%~2"
set "PACK=%~3"

if "%SEAT%"=="" (
  echo.
  echo  Usage: Set-SeatAfterClone.cmd SEAT-ID [WSJT-RIG-NAME] [flex50^|ic9700-144]
  echo  SEAT-ID becomes Windows hostname and WIMS_SEAT_ID.
  echo  WSJT-RIG-NAME is passed as wsjtx --rig-name=...
  echo  PACK defaults: name contains 144/IC/9700 -^> ic9700-144, else flex50.
  echo.
  exit /b 1
)

if "%RIG%"=="" set "RIG=%SEAT%"

if "%PACK%"=="" (
  echo %SEAT% %RIG% | find /I "144" >nul && set "PACK=ic9700-144"
  echo %SEAT% %RIG% | find /I "IC" >nul && set "PACK=ic9700-144"
  echo %SEAT% %RIG% | find /I "9700" >nul && set "PACK=ic9700-144"
  if "%PACK%"=="" set "PACK=flex50"
)
if /I "%PACK%"=="flex" set "PACK=flex50"
if /I "%PACK%"=="ic9700" set "PACK=ic9700-144"
if /I "%PACK%"=="icom" set "PACK=ic9700-144"

REM Sanitize: Windows hostname max 15 chars, no spaces
set "HOST15=%SEAT%"
if not "%HOST15:~15,1%"=="" (
  echo WARN: hostname longer than 15 chars — truncating for Windows NetBIOS
  set "HOST15=%SEAT:~0,15%"
)

echo.
echo  Personalize cloned WIMS seat
echo  ============================
echo  Seat / hostname: %HOST15%
echo  WSJT-X rig-name:  %RIG%
echo  Radio pack:       %PACK%
echo  WIMS server:       http://192.168.1.119:8787
echo.

(
  echo @echo off
  echo REM Shared seat settings ^(generated by Set-SeatAfterClone.cmd^)
  echo set "WIMS_SERVER=http://192.168.1.119:8787"
  echo set "SEAT_DEFAULT_RADIO=%PACK%"
  echo set "START_N1MM=1"
  echo set "START_WSJTX=1"
  echo set "START_AGENT=1"
  echo set "START_AGENT_RESTART=1"
  echo set "N1MM_EXE=C:\Program Files (x86)\N1MM Logger+\N1MMLogger.net.exe"
  echo set "WSJTX_EXE=C:\WSJT\wsjtx\bin\wsjtx.exe"
  echo set "START_DELAY_SEC=5"
  echo set "AGENT_INTERVAL=30"
) > "%HERE%seat-common.cmd"
echo  Wrote seat-common.cmd

if /I "%PACK%"=="flex50" (
  (
    echo @echo off
    echo REM Flex 50 MHz ^(generated by Set-SeatAfterClone.cmd^)
    echo set "SEAT_LABEL=%SEAT%"
    echo set "WIMS_SEAT_ID=%SEAT%"
    echo set "WSJTX_RIG_NAME=%RIG%"
    echo set "SMARTSDR_DIR=C:\Program Files\SmartSDR v4.2.20"
    echo set "START_SMARTSDR_CAT=1"
    echo set "START_SMARTSDR_DAX=1"
    echo set "SMARTSDR_DELAY_SEC=15"
  ) > "%HERE%radio-flex50.cmd"
  echo  Wrote radio-flex50.cmd
  set "LAUNCH=%HERE%Start-Seat-Flex50.cmd"
  set "DESC=WIMS Flex-50 seat pack at logon"
) else (
  (
    echo @echo off
    echo REM IC-9700 144 MHz ^(generated by Set-SeatAfterClone.cmd^)
    echo set "SEAT_LABEL=%SEAT%"
    echo set "WIMS_SEAT_ID=%SEAT%"
    echo set "WSJTX_RIG_NAME=%RIG%"
    echo set "WFVIEW_EXE=C:\Program Files\wfview\wfview.exe"
    echo set "WFVIEW_DELAY_SEC=5"
  ) > "%HERE%radio-ic9700-144.cmd"
  echo  Wrote radio-ic9700-144.cmd
  set "LAUNCH=%HERE%Start-Seat-IC9700-144.cmd"
  set "DESC=WIMS IC9700-144 seat pack at logon"
)

REM Desktop WIMS menu
if exist "%HERE%Install-WIMS-Desktop-Shortcut.cmd" (
  call "%HERE%Install-WIMS-Desktop-Shortcut.cmd" /nopause
)

if exist "%HERE%Install-WSJTX-RigNameShortcuts.cmd" (
  call "%HERE%Install-WSJTX-RigNameShortcuts.cmd" /nopause
)

set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "LNK=%STARTUP%\WIMS Seat.lnk"
if not exist "%STARTUP%" mkdir "%STARTUP%" 2>nul
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('%LNK%'); $s.TargetPath = '!LAUNCH!'; $s.Arguments = '/silent'; $s.WorkingDirectory = '%HERE%'; $s.WindowStyle = 7; $s.Description = '!DESC!'; $s.Save(); Write-Host 'Startup OK'"

for /f "tokens=2 delims==" %%A in ('wmic computersystem get name /value ^| find "="') do set "CUR=%%A"
if /I "%CUR%"=="%HOST15%" (
  echo  Hostname already %HOST15% — no rename.
  goto done
)

echo  Renaming computer %CUR% -^> %HOST15% ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "try { Rename-Computer -NewName '%HOST15%' -Force -ErrorAction Stop; Write-Host 'Rename scheduled — reboot required.' } catch { Write-Host ('Rename failed: ' + $_.Exception.Message); Write-Host 'Run this script elevated (Run as administrator).'; exit 1 }"
if errorlevel 1 exit /b 1

echo.
echo  Reboot now so the new hostname applies, then log on and confirm:
echo    - WIMS agent reports seat %SEAT% on http://192.168.1.119:8787/status
echo    - WSJT-X Outgoing interface = Ethernet, UDP 224.0.0.73:band-port
echo    - N1MM Broadcast = 224.0.0.73:12060
echo.
choice /C YN /M "Reboot now"
if errorlevel 2 goto done
shutdown /r /t 5 /c "WIMS seat rename to %HOST15%"
exit /b 0

:done
echo.
echo  Seat files ready. Start apps:
echo    Start-Seat-Flex50.cmd       ^(50 MHz Flex^)
echo    Start-Seat-IC9700-144.cmd   ^(144 MHz IC-9700^)
echo  Or reboot if hostname was changed.
exit /b 0
