@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM After cloning the Win10 WIMS template, personalize this guest for one radio seat.
REM Usage (elevated recommended for rename):
REM   Set-SeatAfterClone.cmd SEAT-ID [WSJT-RIG-NAME]
REM Examples:
REM   Set-SeatAfterClone.cmd IC9700-50 IC9700-50-FT8
REM   Set-SeatAfterClone.cmd FLEX-8600M FLEX-8600M-FT8
REM
REM What it does:
REM   1) Writes scripts\windows\seat-local.cmd (WIMS_SEAT_ID, optional WSJTX_RIG_NAME)
REM   2) Renames the computer to SEAT-ID (needs reboot)
REM   3) Ensures Startup\WIMS Seat.lnk exists
REM Does NOT change Proxmox USB/network or radio drivers.

cd /d "%~dp0"
set "HERE=%~dp0"
set "SEAT=%~1"
set "RIG=%~2"

if "%SEAT%"=="" (
  echo.
  echo  Usage: Set-SeatAfterClone.cmd SEAT-ID [WSJT-RIG-NAME]
  echo  SEAT-ID becomes Windows hostname and WIMS_SEAT_ID.
  echo  Optional WSJT-RIG-NAME is passed as wsjtx --rig-name=...
  echo.
  exit /b 1
)

REM Sanitize: Windows hostname max 15 chars, no spaces
set "HOST15=%SEAT%"
if not "%HOST15:~15,1%"=="" (
  echo WARN: hostname longer than 15 chars — truncating for Windows NetBIOS
  set "HOST15=%SEAT:~0,15%"
)

echo.
echo  Personalize cloned WIMS seat
echo  ============================
echo  Seat / hostname: %HOST15%
if defined RIG echo  WSJT-X rig-name:  %RIG%
echo  WIMS server:       http://192.168.1.119:8787
echo.

(
  echo @echo off
  echo REM Machine-specific seat settings ^(generated by Set-SeatAfterClone.cmd^)
  echo REM Seat: %SEAT%
  echo.
  echo set "WIMS_SERVER=http://192.168.1.119:8787"
  echo set "WIMS_SEAT_ID=%SEAT%"
  echo.
  echo set "START_N1MM=1"
  echo set "START_WSJTX=1"
  echo set "START_AGENT=1"
  echo set "START_AGENT_RESTART=1"
  echo.
  echo set "N1MM_EXE=C:\Program Files (x86)\N1MM Logger+\N1MMLogger.net.exe"
  echo set "WSJTX_EXE=C:\WSJT\wsjtx\bin\wsjtx.exe"
  if defined RIG (
    echo set "WSJTX_RIG_NAME=%RIG%"
  ) else (
    echo set "WSJTX_RIG_NAME="
  )
  echo.
  echo set "START_DELAY_SEC=5"
  echo set "AGENT_INTERVAL=30"
) > "%HERE%seat-local.cmd"

echo  Wrote %HERE%seat-local.cmd

REM Desktop WIMS menu
if exist "%HERE%Install-WIMS-Desktop-Shortcut.cmd" (
  call "%HERE%Install-WIMS-Desktop-Shortcut.cmd" /nopause
)

REM Logon auto-start
set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "LNK=%STARTUP%\WIMS Seat.lnk"
if not exist "%STARTUP%" mkdir "%STARTUP%" 2>nul
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ws = New-Object -ComObject WScript.Shell; $s = $ws.CreateShortcut('%LNK%'); $s.TargetPath = '%HERE%Start-WimsSeat.cmd'; $s.Arguments = '/silent'; $s.WorkingDirectory = '%HERE%'; $s.WindowStyle = 7; $s.Description = 'Start N1MM, WSJT-X, WIMS agent at logon'; $s.Save(); Write-Host 'Startup OK'"

REM Rename computer if needed
for /f "tokens=2 delims==" %%A in ('wmic computersystem get name /value ^| find "="') do set "CUR=%%A"
if /I "%CUR%"=="%HOST15%" (
  echo  Hostname already %HOST15% — no rename.
  goto done
)

echo  Renaming computer %CUR% -^> %HOST15% ...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "try { Rename-Computer -NewName '%HOST15%' -Force -ErrorAction Stop; Write-Host 'Rename scheduled — reboot required.' } catch { Write-Host ('Rename failed: ' + $_.Exception.Message); Write-Host 'Run this script elevated (Run as administrator).'; exit 1 }"
if errorlevel 1 exit /b 1

echo.
echo  Reboot now so the new hostname applies, then log on and confirm:
echo    - WIMS agent reports seat %SEAT% on http://192.168.1.119:8787/status
echo    - WSJT-X Outgoing interface = Ethernet, UDP 224.0.0.73:band-port
echo    - N1MM Broadcast = 224.0.0.73:12060
echo.
choice /C YN /M "Reboot now"
if errorlevel 2 goto done
shutdown /r /t 5 /c "WIMS seat rename to %HOST15%"
exit /b 0

:done
echo.
echo  Seat files ready. Start apps:  Start-WimsSeat.cmd
echo  Or reboot if hostname was changed.
exit /b 0
